# Generated by Django 5.2.2 on 2025-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_about_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_products',
            field=models.TextField(blank=True, help_text='Brief introduction about the product', null=True),
        ),
    ]
